name: 'CHANGELOG Generator, DAWG!'
description: 'Generates a single-file CHANGELOG from your repository releases, dawg.'
author: 'Mike-EEE'
branding:
  icon: edit
  color: red
inputs:
  security_token:
    description: 'Security context token for the calling repo. Typically this is `$\{{ secrets.GITHUB_TOKEN }}`.'
    required: true
  owner:
    description: 'The owner of the release repository. Defaults to the `GITHUB_OWNER` environment variable.'
    default: ''
    required: false    
  repository:
    description: 'Repository with the releases to query.  Defaults to the `GITHUB_REPOSITORY` environment variable.'
    default: ''
    required: false
runs:
  using: docker
  image: Dockerfile