name: 'CHANGELOG Generator, DAWG!'
description: 'Generates a single-file CHANGELOG from your repository releases, dawg.'
author: 'Mike-EEE'
branding:
  icon: edit
  color: red
inputs:
  security_token:
    description: 'Security context token for the calling repo. Typically this is `$\{{ secrets.GITHUB_TOKEN }}`.'
    required: true
  repository:
    description: 'The repository containing the releases to query in the form of `<Owner>/<Name>`.  Defaults to the `GITHUB_REPOSITORY` environment variable if not provided.'
    default: ''
    required: false
runs:
  using: docker
  image: Dockerfile