name: 'CHANGELOG Generator, DAWG!'
description: 'Generates a single-file CHANGELOG from your repository releases, dawg.'
author: 'Mike-EEE'
branding:
  icon: edit
  color: red
inputs:
  access_token:
    description: 'Security context access token for the identity to perform the query. Typically this is `$\{{ secrets.GITHUB_TOKEN }}`.'
    required: true
  filepath:
    description: The filepath location of where to save the changelog, dawg.
    required: true
    default: "./CHANGELOG.md"
  repository:
    description: 'The repository containing the releases to query in the form of `<Owner>/<Name>`.  Defaults to the `GITHUB_REPOSITORY` environment variable if not provided.'
    required: false
  template:
    description: |
                 Defines the [Mustache](http://mustache.github.io/mustache.5.html) template used to generate the changelog from queried releases.  
                 
                 The `releases` property passed to the template is a set of GitHub releases from their API as defined here:
                 https://developer.github.com/v3/repos/releases/
    default: |
             {{#releases}}
             # [{{ name }}]({{ html_url }})
             > {{ published_at }} UTC
             ##### ``{{ tag_name }}``
             {{ body }}
             {{/releases}}
    required: false
outputs:
#  result:
#    description: The contents of the CHANGELOG, dawg!
  filename:
    description: The name of the file that was saved.
    
runs:
  using: docker
  image: Dockerfile